version: "3.8"
services:
  web:
    container_name: development
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - CLEARDB_DATABASE_URL="${CLEARDB_DATABASE_URL}"